name: Update Google Fonts Map

on:
  schedule:
    - cron: '15 5 23 * *'
  workflow_dispatch: 
  
permissions:
  contents: write

jobs:
  update-fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci

      - run: node generate-map.js
        env:
          GOOGLE_FONTS_API_KEY: ${{ secrets.GOOGLE_FONTS_API_KEY }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="google-fonts-${{ steps.date.outputs.date }}"
          gh release create "$tag" google-fonts.json \
            --title "Google Fonts Library - ${{ steps.date.outputs.date }}" \
            --notes "Automated release of google-fonts.zip on ${{ steps.date.outputs.date }}" \
            --repo ${{ github.repository }}
